### ISSUE TITLE
Fearure request: append file

### ISSUE THREAD

**Issue by dtest505** [digininja/CeWL#12]
I didn't see it in the --help but I'd like to append to a file.
(ie: spider 4 sites into a single text file)

**Comment by digininja** [comment]
That could be interesting. They would have to run serially to save having
to mess around with threading and locking word lists.

If that was the case, going off site was not allowed, but site one pointed
at site two, what would happen. I think I'd have to say don't follow the
link otherwise site two could get spidered twice.

**Comment by digininja** [comment]
Think this is going to be too complex to add.
