### ISSUE TITLE
add the possibility to include numbers and kind of a sentence mode

### ISSUE THREAD

**Issue by stahnirockt** [digininja/CeWL#33]
I had the following ideas in mind and integrated them into my fork of your project.

1) the ability to integrate numbers so that I can create a list of words, numbers (e.g., for dates), or both.

2) the possibility of a 'sentence_mode'.
Often passwords are formed with the help of phrases. So words of a sentence combined, or lined up the initial letters. I thought it would be great to get a wordlist as a result. For example 'This is a simple test' becomes 'Tiast'.

Maybe you want to look at my fork and integrate this. I could also generate a pull request, but I think it's not well coded because some parts seem redundant and could maybe replaced by a function. For me coding is just a hobby.

**Comment by digininja** [comment]
How useful do you think the sentence mode would be? I understand passwords
from sentences but how often are they likely to be sentences on a web site?

The numbers bit could be useful.

If you want to improve the code a bit, you could pull the sentence.each bit
out and run it at the end of the case statement. You'd just need to set
sentence rather than words in case 1 (I think).

Your validation on line 645 and 648 is checking depth not the correct
variables.

Typo on line 536, 2ja rather than just 2.

Fix those up and I'll check it out and have a play with it, I'll ask a few
friends who use it what their opinion on the sentence mode, see if they see
it as something that they would use.

Robin

**Comment by stahnirockt** [comment]
Thanks you for your very fast and helpful feedback.
 I fixed the typo and the validation. Will look at your suggested improvement tomorrow.

I think the 'sentence mode' can be useful when thinking of quotes, movie-, book-, song- or album titles and the like. 
But that's the nice thing about open source. Even if you do not use it, I can use it :-).

**Comment by digininja** [comment]
You would need to make sure that the quotes were in the right format on the
site. I can see the logic and use case, just wondering if there are enough
instances of the data being formatted correctly to be useful. But even if I
include it and no one except you uses it then nothing is lost.

**Comment by digininja** [comment]
One more thought, could you add a description for the regex's you've used,
it will make debugging them a lot easier if I ever have to.
