### ISSUE TITLE
Broken dependency: spider

### ISSUE THREAD

**Issue by kevin-ott** [digininja/CeWL#34]
It seems that on the latest version of Kali, CeWL is broken because of a depreciated function? in the spider library:

```bash
./cewl.rb -d 2 wikipedia.org
CeWL 5.4.2 (Break Out) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
/usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:125: warning: constant ::Fixnum is deprecated
```

Dependencies were installed today with gem install.

```
gem list --local | grep spider
spider (0.32, 0.5.1)
```

Anything I'm missing?

**Comment by kevin-ott** [comment]
So after some more testing, CeWL failed silently because I omitted the "https://" portion of the URL. The Fixnum error persists, but the tool runs nonetheless.

**Comment by digininja** [comment]
It won't have failed but it will have taken the URL without a protocol to be http://wikipedia.org and will then have refused to follow the redirect to https://wikipedia.org because that is off site as far as it is concerned.

There is nothing I can do about the message from the gem, the spider I built the app on is very old and creaky and I've already patched loads of it up. I need to do a rewrite on top of a decent spider but don't have the time at the moment.
