### ISSUE TITLE
Cewl does nothing.

### ISSUE THREAD

**Issue by 1machiene** [digininja/CeWL#81]
hi,
i am trying to use the newest version of cewl but when i type smth in i allways get this message:

CeWL 5.4.8 (Inclusion) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

and nothing more. And i have my terminal back.

How can i get cewl to work?

(i tryed for the example the following comand: cewl -m 6 -w testlist.txt -c  bbc.com)

**Comment by digininja** [comment]
The version you are using is about five months out of date, the current
version is 5.5.2, that shouldn't make much difference but please try the
latest version from this repo for any further tests.

The reason you aren't getting anything back is because bbc.com redirects to
https://bbc.com which then redirects to https://www.bbc.com. CeWL will only
scan the site it is told to so it sees the redirect and quits straight
away. If you want some data, you'll need to tell it to scan
https://www.bbc.com but watch out, that is probably quite a big site so
scanning it will probably take a long time.

**Comment by 1machiene** [comment]
ah ok sry i forgot the "https://www."
sorry. now it works

**Comment by digininja** [comment]
Great, please close the ticket.

**Comment by 1machiene** [comment]
ok thanks
